### ISSUE TITLE
Pb d'image

### ISSUE THREAD

**Issue by arnaudlevy** [osunyorg/sinonvirgule-site#7]
<img width="1792" alt="Capture d’écran 2024-02-20 à 22 06 38" src="https://github.com/noesya/sinonvirgule-site/assets/2088968/27738267-f22e-4490-a49e-a19ff2f872ed">

https://www.sinonvirgule.fr/nos-projets/2023-09-10-deviations-plastiques-x-plastic-odyssey/

**Comment by Olivia206** [comment]
C'est à cause de l'override du style, @arnaudlevy tu sais si le block image devait avoir un comportement différent du thème en landscape ? Je ne trouve pas d'exemple dans les maquettes

**Comment by arnaudlevy** [comment]
Je ne sais pas mais je penche plutôt pour une erreur

**Comment by Olivia206** [comment]
Y'a aussi un forçage de la taille des images dans le bloc image, je viens de voir que celles en portrait apparaissent en landscape, c'est aussi une erreur ?

![Capture d’écran 2024-02-26 à 09 59 36](https://github.com/noesya/sinonvirgule-site/assets/91660674/353b8407-07ba-4d20-8edd-20737a9555fc)

**Comment by arnaudlevy** [comment]
Je sais pas. Qui a intégré ?

**Comment by Olivia206** [comment]
Toi haha : https://github.com/noesya/sinonvirgule-site/commit/fde0b059a5d164cff90bcf60795bd02cea6f88f1

**Comment by arnaudlevy** [comment]
J'ai encore fait une connerie !!!

**Comment by arnaudlevy** [comment]
@Olivia206 tu peux enlever mes bêtises stp ? Merci !

**Comment by Olivia206** [comment]
yes c'est fait
